/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Home2RouteImport } from './routes/home2'
import { Route as Home3RouteImport } from './routes/home3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Home2Route = Home2RouteImport.update({
  id: '/home2',
  path: '/home2',
  getParentRoute: () => rootRouteImport,
} as any)
const Home3Route = Home3RouteImport.update({
  id: '/home3',
  path: '/home3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home2': typeof Home2Route
  '/home3': typeof Home3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home2': typeof Home2Route
  '/home3': typeof Home3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home2': typeof Home2Route
  '/home3': typeof Home3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home2' | '/home3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home2' | '/home3'
  id: '__root__' | '/' | '/home2' | '/home3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Home2Route: typeof Home2Route
  Home3Route: typeof Home3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home2': {
      id: '/home2'
      path: '/home2'
      fullPath: '/home2'
      preLoaderRoute: typeof Home2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home3': {
      id: '/home3'
      path: '/home3'
      fullPath: '/home3'
      preLoaderRoute: typeof Home3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Home2Route: Home2Route,
  Home3Route: Home3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
